# Program tabel perkalian dengan validasi nama

# input nama
nama_benar = "zacky"  # ganti dengan nama pendek kamu
nama = input("Masukkan nama anda: ")

if nama == nama_benar:
    print("Nama benar, lanjut ke program...\n")

    # input angka
    angka = int(input("Masukkan angka: "))

    print("\nTabel perkalian:")
    for i in range(1, 11):
        print(f"{angka} x {i} = {angka * i}")

else:
    print("Silahkan coba lagi")